# Generated by Django 4.0.6 on 2022-10-04 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_photo_alter_partenaire_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='resp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bob', to=settings.AUTH_USER_MODEL),
        ),
    ]
