# Generated by Django 4.0.6 on 2022-10-06 19:32

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_partenaire_resp_alter_structure_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=85, scale=None, size=[250, 350], upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=-1, scale=None, size=[500, 800], upload_to='ville'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=-1, scale=None, size=[800, 900], upload_to='salle'),
        ),
    ]
