# Generated by Django 4.0.6 on 2022-10-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_option_approved_alter_myuser_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='approved',
        ),
    ]
