# Generated by Django 4.0.6 on 2022-10-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_myuser_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='partenaires',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structure',
            name='structures',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
