# Generated by Django 4.0.6 on 2022-10-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_structure_partenaires_structure_structures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='partenaires',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='structures',
        ),
        migrations.AddField(
            model_name='myuser',
            name='partenaires',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='structures',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
